FROM node:22-alpine

WORKDIR /usr/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8000

CMD [ "sh", "-c", "npx prisma generate --force-reset && npx prisma db push && npm run dev" ]

